[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Maps"
  url = "maps/"
  weight = -110 # Sets the menu order 

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "File Browser"
  url = "/files/"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/"
[[main]]
  parent = "Links"
  name = "Jupyter Notebook"
  url = "/jupyter/"
[[main]]
  parent = "Links"
  name = "Geoserver"
  url = "/geoserver/"
[[main]]
  parent = "Links"
  name = "Node Red"
  url = "/node-red/"
[[main]]
  parent = "Links"
  name = "Postgrest"
  url = "/api/"
[[main]]
  parent = "Links"
  name = "Node Red"
  url = "/node-red/"
[[main]]
  parent = "Links"
  name = "Swagger"
  url = "/swagger/" 
[[main]]
  parent = "Links"
  name = "Mapproxy"
  url = "/mapproxy/" 

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/timlinux"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/timlinux"
#[[social]]
#  name = "linkedin"
#  weight = 3
#  url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"